# Generated by Django 5.2.6 on 2025-10-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nota1', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nota2', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nota3', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fecha_ingreso', models.DateField()),
                ('carrera', models.CharField(choices=[('INFORMATICA', 'Informática'), ('ADMINISTRACION', 'Administración'), ('MECANICA', 'Mecánica'), ('CONSTRUCCION', 'Construcción'), ('ROBOTICA', 'Robótica'), ('CONTABILIDAD', 'Contabilidad')], max_length=20)),
            ],
        ),
    ]
